package com.studiomuda.estoque.controller;
import com.studiomuda.estoque.jpa.entity.*; import com.studiomuda.estoque.jpa.repository.*; import com.studiomuda.estoque.proxy.*; import com.studiomuda.estoque.security.UsuarioAutenticado; import com.studiomuda.estoque.service.*;
import org.springframework.security.core.Authentication; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.mvc.support.RedirectAttributes;
@Controller @RequestMapping("/frete") public class FreteController {
 private final CotacaoFreteService cotacoes; private final TransportadoraService transportadoras; private final ContingenciaService contingencias; private final DespachoService despachos; private final PedidoJpaRepository pedidos; private final ClienteJpaRepository clientes;
 public FreteController(CotacaoFreteService c,TransportadoraService t,ContingenciaService f,DespachoService d,PedidoJpaRepository p,ClienteJpaRepository cl){cotacoes=c;transportadoras=t;contingencias=f;despachos=d;pedidos=p;clientes=cl;}
 @GetMapping public String inicio(Model m){m.addAttribute("cotacoes",cotacoes.listarHistorico());m.addAttribute("transportadoras",transportadoras.listar());m.addAttribute("faixas",contingencias.listar());m.addAttribute("ordens",despachos.listar());return "frete/index";}
 @GetMapping("/cotacao") public String cotacao(Model m){if(!m.containsAttribute("parametros"))m.addAttribute("parametros",new ParametrosCotacao());m.addAttribute("pedidos",pedidos.findAll());m.addAttribute("clientes",clientes.findAllByOrderByNomeAsc());return "frete/cotacao";}
 @PostMapping("/cotacao") public String cotar(@ModelAttribute ParametrosCotacao p,Authentication a,RedirectAttributes r){try{r.addFlashAttribute("resultado",cotacoes.cotar(p,usuarioId(a)));r.addFlashAttribute("mensagem","Cotacao realizada com sucesso.");}catch(RuntimeException e){r.addFlashAttribute("mensagemErro",e.getMessage());r.addFlashAttribute("parametros",p);}return "redirect:/frete/cotacao";}
 @GetMapping("/historico") public String historico(Model m){m.addAttribute("cotacoes",cotacoes.listarHistorico());return "frete/historico";}
 @GetMapping("/transportadoras") public String transportadoras(Model m){if(!m.containsAttribute("transportadora"))m.addAttribute("transportadora",new TransportadoraJpaEntity());m.addAttribute("transportadoras",transportadoras.listar());return "frete/transportadoras";}
 @PostMapping("/transportadoras") public String salvarTransportadora(@ModelAttribute TransportadoraJpaEntity t,RedirectAttributes r){try{transportadoras.salvar(t);r.addFlashAttribute("mensagem","Transportadora salva.");}catch(RuntimeException e){r.addFlashAttribute("mensagemErro",e.getMessage());}return "redirect:/frete/transportadoras";}
 @PostMapping("/transportadoras/{id}/alternar-status") public String alternarTransportadora(@PathVariable Integer id,RedirectAttributes r){try{transportadoras.alternarStatus(id);r.addFlashAttribute("mensagem","Status da transportadora atualizado.");}catch(RuntimeException e){r.addFlashAttribute("mensagemErro",e.getMessage());}return "redirect:/frete/transportadoras";}
 @GetMapping("/contingencia") public String contingencia(Model m){if(!m.containsAttribute("faixa"))m.addAttribute("faixa",new TabelaContingenciaJpaEntity());m.addAttribute("faixas",contingencias.listar());m.addAttribute("transportadoras",transportadoras.listarAtivas());return "frete/contingencia";}
 @PostMapping("/contingencia") public String salvarContingencia(@ModelAttribute("faixa") TabelaContingenciaJpaEntity f,@RequestParam(required=false) Integer transportadoraId,RedirectAttributes r){try{contingencias.salvar(f,transportadoraId);r.addFlashAttribute("mensagem","Faixa de contingencia salva.");}catch(RuntimeException e){r.addFlashAttribute("mensagemErro",e.getMessage());}return "redirect:/frete/contingencia";}
 @PostMapping("/contingencia/{id}/alternar-status") public String alternarContingencia(@PathVariable Integer id,RedirectAttributes r){try{contingencias.alternarStatus(id);r.addFlashAttribute("mensagem","Status da faixa atualizado.");}catch(RuntimeException e){r.addFlashAttribute("mensagemErro",e.getMessage());}return "redirect:/frete/contingencia";}
 @GetMapping("/despacho") public String despacho(Model m){m.addAttribute("pedidos",pedidos.findAll());m.addAttribute("cotacoes",cotacoes.listarHistorico());m.addAttribute("transportadoras",transportadoras.listarAtivas());return "frete/despacho";}
 @PostMapping("/despacho") public String gerarDespacho(@RequestParam Integer pedidoId,@RequestParam Integer logCotacaoId,@RequestParam Integer transportadoraId,RedirectAttributes r){try{OrdemDespachoJpaEntity o=despachos.gerarOrdemDespacho(pedidoId,logCotacaoId,transportadoraId);r.addFlashAttribute("mensagem","Ordem #"+o.getId()+" gerada com sucesso.");return "redirect:/frete/despachos";}catch(RuntimeException e){r.addFlashAttribute("mensagemErro",e.getMessage());return "redirect:/frete/despacho";}}
 @GetMapping("/despachos") public String despachos(Model m){m.addAttribute("ordens",despachos.listar());return "frete/despachos";}
 private Integer usuarioId(Authentication a){if(a!=null&&a.getPrincipal() instanceof UsuarioAutenticado)return ((UsuarioAutenticado)a.getPrincipal()).getId();return 1;}
}
