package com.studiomuda.estoque.jpa.entity;
import javax.persistence.*; import java.math.BigDecimal; import java.time.LocalDateTime;
@Entity @Table(name="log_cotacao")
public class LogCotacaoJpaEntity {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Integer id; @Column(name="usuario_id",nullable=false) private Integer usuarioId;
 @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="cliente_id") private ClienteJpaEntity cliente; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="pedido_id") private PedidoJpaEntity pedido;
 @Column(name="cep_destino",nullable=false,length=8) private String cepDestino; @Column(nullable=false) private BigDecimal peso; @Column(nullable=false) private BigDecimal comprimento; @Column(nullable=false) private BigDecimal largura; @Column(nullable=false) private BigDecimal altura;
 @Column(name="hash_parametros",nullable=false,length=64) private String hashParametros; @Column(name="valor_cotado",nullable=false) private BigDecimal valorCotado; @Column(name="origem_resultado",nullable=false,length=20) private String origemResultado;
 @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="transportadora_id") private TransportadoraJpaEntity transportadora; @Column(name="data_cotacao",nullable=false) private LocalDateTime dataCotacao;
 public Integer getId(){return id;} public void setId(Integer v){id=v;} public Integer getUsuarioId(){return usuarioId;} public void setUsuarioId(Integer v){usuarioId=v;} public ClienteJpaEntity getCliente(){return cliente;} public void setCliente(ClienteJpaEntity v){cliente=v;} public PedidoJpaEntity getPedido(){return pedido;} public void setPedido(PedidoJpaEntity v){pedido=v;}
 public String getCepDestino(){return cepDestino;} public void setCepDestino(String v){cepDestino=v;} public BigDecimal getPeso(){return peso;} public void setPeso(BigDecimal v){peso=v;} public BigDecimal getComprimento(){return comprimento;} public void setComprimento(BigDecimal v){comprimento=v;} public BigDecimal getLargura(){return largura;} public void setLargura(BigDecimal v){largura=v;} public BigDecimal getAltura(){return altura;} public void setAltura(BigDecimal v){altura=v;}
 public String getHashParametros(){return hashParametros;} public void setHashParametros(String v){hashParametros=v;} public BigDecimal getValorCotado(){return valorCotado;} public void setValorCotado(BigDecimal v){valorCotado=v;} public String getOrigemResultado(){return origemResultado;} public void setOrigemResultado(String v){origemResultado=v;} public TransportadoraJpaEntity getTransportadora(){return transportadora;} public void setTransportadora(TransportadoraJpaEntity v){transportadora=v;} public LocalDateTime getDataCotacao(){return dataCotacao;} public void setDataCotacao(LocalDateTime v){dataCotacao=v;}
}
