package com.studiomuda.estoque.jpa.entity;
import javax.persistence.*; import java.math.BigDecimal; import java.time.LocalDateTime;
@Entity @Table(name="ordem_despacho")
public class OrdemDespachoJpaEntity {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Integer id;
 @ManyToOne(optional=false,fetch=FetchType.EAGER) @JoinColumn(name="pedido_id") private PedidoJpaEntity pedido; @ManyToOne(optional=false,fetch=FetchType.EAGER) @JoinColumn(name="transportadora_id") private TransportadoraJpaEntity transportadora; @ManyToOne(optional=false,fetch=FetchType.EAGER) @JoinColumn(name="log_cotacao_id") private LogCotacaoJpaEntity logCotacao;
 @Column(name="valor_frete",nullable=false) private BigDecimal valorFrete; @Column(nullable=false,length=20) private String status="PENDENTE"; @Column(name="codigo_rastreio") private String codigoRastreio; @Column(name="data_despacho") private LocalDateTime dataDespacho; @Column(name="data_entrega_prevista") private LocalDateTime dataEntregaPrevista; @Column(name="data_entrega_realizada") private LocalDateTime dataEntregaRealizada;
 public Integer getId(){return id;} public void setId(Integer v){id=v;} public PedidoJpaEntity getPedido(){return pedido;} public void setPedido(PedidoJpaEntity v){pedido=v;} public TransportadoraJpaEntity getTransportadora(){return transportadora;} public void setTransportadora(TransportadoraJpaEntity v){transportadora=v;} public LogCotacaoJpaEntity getLogCotacao(){return logCotacao;} public void setLogCotacao(LogCotacaoJpaEntity v){logCotacao=v;} public BigDecimal getValorFrete(){return valorFrete;} public void setValorFrete(BigDecimal v){valorFrete=v;} public String getStatus(){return status;} public void setStatus(String v){status=v;} public String getCodigoRastreio(){return codigoRastreio;} public void setCodigoRastreio(String v){codigoRastreio=v;} public LocalDateTime getDataDespacho(){return dataDespacho;} public void setDataDespacho(LocalDateTime v){dataDespacho=v;} public LocalDateTime getDataEntregaPrevista(){return dataEntregaPrevista;} public void setDataEntregaPrevista(LocalDateTime v){dataEntregaPrevista=v;} public LocalDateTime getDataEntregaRealizada(){return dataEntregaRealizada;} public void setDataEntregaRealizada(LocalDateTime v){dataEntregaRealizada=v;}
}
